### ISSUE TITLE
As a developer, I would like to have a system to check event logs

### ISSUE THREAD

**Issue by rabiarsl** [SiriusGroupProject/RecyclingProjectMain#11]
This component aims to keep logs of events that may occur in our system in a certain format (with logging level and time stamp) and in a certain place. For example, let us have an event such as  "on 14.01.2020 at 11:30, Ali Kaya, who had the id number 1 threw the branded ERIKLI bottle in the automata which had the id number 12 in Cankaya".

**Comment by eyuksekkolasin** [comment]
Amazon Web Service S3 is added for logging
