### ISSUE TITLE
As a developer, I want to connect and communicate with automat from mobile app. 

### ISSUE THREAD

**Issue by rabiarsl** [SiriusGroupProject/RecyclingProjectMain#3]
Each of the automats must have a QR code on its display. When any user comes to the automat and scan its QR code by using mobile app, a connection should be established between automat and the mobile app which is using by the user.
This connection will be established by a server at the middle of mobile app's client and automat. 

When QR code is scanned, an HTTP request that includes connection parameters will be sended to "connection server". After that, the connection server will forward the parameters through the automat and wait for the response. The last process is that automat will send its response for connection to the connection server and depending on the response, the connection will be established or not. The schema of these processes is below.

In this issue, the purpose is to implement the connection server. 
![Untitled Diagram](https://user-images.githubusercontent.com/35258983/72761153-1e022880-3bec-11ea-96d9-7fca51a394d7.jpg)

**Comment by maymayan** [comment]
Each of the automats must have a QR code on its display. When any user comes to the automat and scan its QR code by using mobile app, a connection should be established between automat and the mobile app which is using by the user.
This connection will be established by a server at the middle of mobile app's client and automat. 

When QR code is scanned, an HTTP request that includes connection parameters will be sended to "connection server". After that, the connection server will forward the parameters through the automat and wait for the response. The last process is that automat will send its response for connection to the connection server and depending on the response, the connection will be established or not. The schema of these processes is below.

In this issue, the purpose is to implement the connection server. 
![Untitled Diagram](https://user-images.githubusercontent.com/35258983/72761153-1e022880-3bec-11ea-96d9-7fca51a394d7.jpg)

**Comment by eyuksekkolasin** [comment]
**Closed Issues**

1. Connection Server was roughly done

**Comment by eyuksekkolasin** [comment]
**Closed Issued**

1. All bugs are fixed
