### ISSUE TITLE
As a developer, I would like to develop a backend providing APIs over HTTP to manage the system

### ISSUE THREAD

**Issue by rabiarsl** [SiriusGroupProject/RecyclingProjectMain#5]
This component should provide APIs over HTTP.

The features it should support are as follows:

### **ListUsers**
An API endpoint to list users in the system. This should access the database and retrieve the list of users in the system and return them. The call should be in the following json format.
```
<
UserName : "String", 
UserSurname : "String", 
UserEmail : "String", 
UserBalance : "float", 
UserAdmin : "boolean",  
UserPassword : "String"
> 
```
The return data should be a JSON similar to :
```
{
  users: [
    {
         name: "enes",
	 surname: "yuksekkolasin",
	 email : "eyuksek@gmail.com",
	 balance : 3.50,
	 admin : true,
	 password : "123456"
    },
    {
         name: "mustafa",
	 surname: "aymayan",
	 email : "maymayan@gmail.com",
	 balance : 4.25,
	 admin : false,
	 password : "654321"
    }
  ]
}
```
### **ListAutomats**
An API endpoint to list automats in the system. This should access the database and retrieve the list of automats in the system and return them. The call should be in the following json format.
```
<
AutomatId : "String", 
AutomatOverallVolume : "float", 
AutomatCapacity : "float", 
AutomatActive : "boolean", 
NumberOfBottles : "integer", 
AutomatLocation : "Location",
AutomatBaseConnection : "float"
> 
```
The return data should be a JSON similar to :
```
{
  automats: [
   {
	id: "1",
        overallVolume: 10.0,
	capacity: 70.50,
	active: true,
	numberOfBottles : 20,
	location : {
	   province: "Ankara",
	   district: "Cankaya",
	   neighborhood: "Bahcelievler",
           latitude: "39.920200",
           longitude: "32.826866"
	},
        baseConnection: {
	   connectedUserId: "eyuksek@etu.edu.tr",
	   automatIsAcceptUser: true,
	   scannedBarcode: "4444444",
           verified: "2",
           result: "2"
	}
    }
  ]
}
```
### **ListBottles**
An API endpoint to list bottles in the system. This should access the database and retrieve the list of bottles in the system and return them. The call should be in the following json format.
```
<
BottleBarcode : "String", 
BottleName : "String", 
BottleType : "String", 
BottlePrice : "float"
BottleVolume : "float"
>
```
The return data should be a JSON similar to :
```
{
  bottles: [
    {
	 barcode: "1874654",
	 name: "coco-cola",
	 type : "glass",
	 price : 0.25,
	 volume : 0.3
    },
    {
	 barcode: "5471284",
	 name: "erikli",
	 type : "plastic",
	 price : 0.24,
	 volume : 0.5
    }
  ]
}
```

**Comment by eyuksekkolasin** [comment]
This component should provide APIs over HTTP.

The features it should support are as follows:

### **ListUsers**
An API endpoint to list users in the system. This should access the database and retrieve the list of users in the system and return them. The call should be in the following json format.
```
<
UserId : "String", 
UserName : "String", 
UserSurname : "String", 
UserEmail : "String", 
UserBalance : "float", 
UserType : "boolean",  
UserPassword : "String"
> 
```
The return data should be a JSON similar to :
```
{
  users: [
    {
         id: "1",
         name: "enes",
	 surname: "yuksekkolasin",
	 email : "eyuksek@gmail.com",
	 balance : 3,50,
	 type : "admin",
	 password : "123456"
    },
    {
         id: "2",
         name: "mustafa",
	 surname: "aymayan",
	 email : "maymayan@gmail.com",
	 balance : 4,25,
	 type : "admin",
	 password : "654321"
    }
  ]
}
```
**### ListAutomats**
An API endpoint to list automats in the system. This should access the database and retrieve the list of automats in the system and return them. The call should be in the following json format.
```
<
AutomatId : "String", 
AutomatCapacity : "float", 
AutomatState : "boolean", 
NumberOfBottles : "integer", 
AutomatLocation : "location"
> 
```
The return data should be a JSON similar to :
```
{
  automats: [
    {
     id: "1",
     capacity: "70.50",
	 state: "active",
	 numberOfBottles : 20,
	 location : {
		neighborhood : "Mimar Sinan",
		street : "72",
		no: "3/9"
	 }
    },
    {
     id: "2",
     capacity: "65,0",
	 state: "active",
	 numberOfBottles : 17,
	 location : {
		neighborhood : "Bahcelievler",
		street : "7",
		no: "3/9"
	 }
    }
  ]
}
```
**### ListBottles**
An API endpoint to list bottles in the system. This should access the database and retrieve the list of bottles in the system and return them. The call should be in the following json format.
```
<
BottleId : "String", 
BottleName : "String", 
BottleBarcode : "String", 
BottleType : "String", 
BottlePrice : "float"
BottleVolume : "float"
>
```
The return data should be a JSON similar to :
```
{
  bottles: [
    {
	 id: "1",
	 name: "coco-cola",
	 barcode: "1874654",
	 type : "glass",
	 price : "0,25",
	 volume : "0,20"
    },
    {
	 id: "2",
	 name: "erikli",
	 barcode: "5471284",
	 type : "glass",
	 price : "0,24",
	 volume : "0,33"
    }
  ]
}
```

**Comment by eyuksekkolasin** [comment]
### **Done Issues**
1. Web Server / Application Server inserted.
2. Database - Web Server connection inserted.
3. Layers (Controller, Model, Repository, Service) added.
4. Automat services inserted.
5. User services inserted

**Comment by eyuksekkolasin** [comment]
### **Closed Issues**
1.Automat services bug fix

**Comment by eyuksekkolasin** [comment]
### **Closed Issues**

1. Bottle services inserted.
2. Services were roughly done.

**Comment by eyuksekkolasin** [comment]
### **Closed Issues**

1. User password hashed.
2. All bugs were fixed in services

**Comment by eyuksekkolasin** [comment]
**Closed Issues**
Upon request from my teammates :

1. When the automat is full, it was automatically deactivated.
2. The remaining capacity of the automat was automatically calculated as a percentage when a bottle was added to the automat.
