### ISSUE TITLE
As a user, I want to have a mobile application to interact with the automat.

### ISSUE THREAD

**Issue by rabiarsl** [SiriusGroupProject/RecyclingProjectMain#6]
This Native Android application should provide a user friendly interface with effective actions to connect and interact with the automat.

**It should mainly talk to the connection server implemented in #3 and the API's provided by #5 .** 

After a user has access to the application and would like to recycle a bottle, a page should provide a list of all the automats that are active and close to the user by using their location. The list should display the automats' distances to the user by meter or kilometer using a third party API and their capacities using the API provided in #5 so that the user can decide which automat would cater to their needs.

Then, the user should have the option to connect with the automat of their choice by scanning the QR code displayed on the automat's screen. If successfully scanned, a connection should be established between the user and the automat using the connection server provided in #3.

After the connection, an information page should be provided to assist the user by stating clear commands regarding the scanning of the bottle's barcode. With this information, the user should be able to scan the bottle's barcode using the interface provided in the next page. The input of this scan should be transferred to an API provided in #5  to receive information about the bottle such as its type and volume. This information should be transferred to the automat using the API provided in #3 .

After the bottle is securely placed inside the automat, the user should notify the automat using the next page so that the automat should be ready to start its process. While the automat is processing, a simple waiting page should be shown until an approval from the automat is received.

After the interaction with the automat is over, the pages implemented in #7 regarding the balance of the user should be shown.

**Comment by nur-yilmaz** [comment]
The main page of the app which is the listing automats page has been changed to a map that displays where all active automats are located.
